version: '2'

services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8700:6000"
  backend1:
    environment:
      - PORT=6001
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back1
    ports:
      - "6001:6001"
    links:
      - db
  backend2:
    environment:
      - PORT=6002
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back2
    ports:
      - "6002:6002"
    links:
      - db
  backend3:
    environment:
      - PORT=6003
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back3
    ports:
      - "6003:6003"
    links:
      - db

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod
volumes:
  mongodb:
  mongodb_config: